//types

export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_HEADERMENU = 'COLLAPSE_HEADERMENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const PAGE_TYPE = 'PAGE_TYPE';
