name: React deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
    paths:
      - "react/**"
  #pull_request:
  #  types:
  #    - closed
  #  branches:
  #    - main

jobs:
  #if_merged:
  #  if: github.event.pull_request.merged == true
  React-Deploy:
    name: 🎉 React Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: 🔨 Build Project
        run: |
          cd react
          corepack yarn install
          corepack yarn build

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: "react/dist/"
          REMOTE_HOST: 192.34.62.123
          REMOTE_USER: dashboardkit-old
          TARGET: public_html/react/free
          EXCLUDE: "/react/node_modules/"
